apiVersion: v1
kind: Service
metadata:
  name: java-app1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: java-app1
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080

